BEGIN;

GRANT CONNECT ON DATABASE ":DATABASE_NAME" TO :DATABASE_OWNER;
GRANT CONNECT ON DATABASE ":DATABASE_NAME" TO :ROLE_VIEWER;
GRANT ALL ON DATABASE ":DATABASE_NAME" TO :DATABASE_OWNER;

ALTER SCHEMA public OWNER TO :DATABASE_OWNER;

GRANT :ROLE_VIEWER TO :ROLE_USER;
GRANT :ROLE_USER TO :ROLE_ADMIN;
GRANT :ROLE_ADMIN TO :DATABASE_OWNER;

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

COMMIT;