name: Lint & TS

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.after
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Corepack
        run: |
          corepack enable
        with:
          node-version: '20.5'
      - run: pnpm install
      - name: Checkout latest commit
        run: |
          git fetch origin
          git checkout ${GITHUB_SHA}
      - name: Run lint-staged
        run: |
          pnpm exec lint-staged